---
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      enabled: true
      ribbon:
        mode: POD
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 1000ms
      routes:
        - id: service
          uri: lb://service-a
          predicates:
            - Path=/1234/**
      default-filters:
        - CircuitBreaker=myCircuitBreaker
        - name: Retry
          args:
            retries: 3
            series: # empty

server:
  port: 8080

logging:
  level:
    root: INFO
    com.dveamer.gateway: DEBUG
    reactor.netty.http.server.AccessLog: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"