---
spring:
  active: dev
  application:
    name: test-boot-app

  cloud:
    config:
      server:
        git:
          uri: http://github.com/study/platform-mgmt.git
          username: xxxxx
          password: xxxxx
          searchPaths: /study/cf/cf-config-server
        bootstrap: true


  security:
    user: 
      name: admin
      password: admin
      
management:
  security:
     enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

        
        