---
spring:
  application:
    name: test-boot-app-client1
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://service-registry-xxxxxx-8330-xxxx-a7ac-bb13cc602257.apps.{DOMAIN}/eureka/
    enabled: true
    oauth2:
      accessTokenUri: https://uaa.sys.{DOMAIN}:443/oauth/token
      clientId: xxxxxx
      clientSecret: xxxxxxx

server:
  port: 1235