---
spring:
  application:
    name: gateway
server:
  port: 8080

logging:
  level:
    root: INFO
    com.dveamer.gateway: DEBUG
    reactor.netty.http.server.AccessLog: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"